name: Record Commit ID

on:
  push:
    branches:
      - '**'  # 监听所有分支的推送事件

jobs:
  record-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Write Commit ID to File
        run: |
          echo "${{ github.sha }}" > commit

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Record commit ID: ${{ github.sha }}'
          add: 'commit'